  // Your web app's Firebase configuration
  var firebaseConfig = {
    apiKey: "AIzaSyDsznE_45f7HYVVFpI226YvljDzIztUnY8",
    authDomain: "letschatwebapp-p94.firebaseapp.com",
    projectId: "letschatwebapp-p94",
    storageBucket: "letschatwebapp-p94.appspot.com",
    messagingSenderId: "402227220694",
    appId: "1:402227220694:web:b1cda9b83b0649f5437977"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);